name: GitGuard Security Scan

on:
  push:
  pull_request:

jobs:
  secret-scan:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install GitGuard
        run: pip install .

      - name: Run GitGuard
        run: gitguard scan .